#!/bin/bash

# wget -O ~/.zshrc http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
wget -O ~/.emacs.d/site-lisp/undo-tree.el http://www.dr-qubit.org/undo-tree/undo-tree.el
wget -O ~/.emacs.d/site-lisp/highlight-parentheses.el http://nschum.de/src/emacs/highlight-parentheses/highlight-parentheses.el
wget -O ~/.emacs.d/site-lisp/pandoc-mode.el https://raw.github.com/joostkremers/pandoc-mode/master/pandoc-mode.el
wget -O ~/.emacs.d/site-lisp/typopunct.el http://www.emacswiki.org/emacs/download/typopunct.el
wget -O ~/.emacs.d/site-lisp/coffee-mode.el https://raw.github.com/defunkt/coffee-mode/master/coffee-mode.el